[2022-11-07T23:26:56.656-0300] {processor.py:156} INFO - Started process (PID=965181) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:26:56.657-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:26:56.657-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:26:56.657-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:26:56.662-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:26:56.660-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:26:56.663-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:26:56.684-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.031 seconds
[2022-11-07T23:27:36.676-0300] {processor.py:156} INFO - Started process (PID=965400) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:27:36.680-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:27:36.681-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:27:36.681-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:27:36.686-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:27:36.685-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:27:36.686-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:27:36.707-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.038 seconds
[2022-11-07T23:28:13.703-0300] {processor.py:156} INFO - Started process (PID=965475) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:28:13.706-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:28:13.707-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:28:13.707-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:28:13.713-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:28:13.712-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:28:13.714-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:28:13.745-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.046 seconds
[2022-11-07T23:28:50.447-0300] {processor.py:156} INFO - Started process (PID=965552) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:28:50.450-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:28:50.450-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:28:50.450-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:28:50.454-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:28:50.453-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:28:50.454-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:28:50.503-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.063 seconds
[2022-11-07T23:29:26.622-0300] {processor.py:156} INFO - Started process (PID=965623) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:29:26.624-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:29:26.625-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:29:26.625-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:29:26.629-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:29:26.628-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:29:26.629-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:29:26.653-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.033 seconds
[2022-11-07T23:29:57.219-0300] {processor.py:156} INFO - Started process (PID=965684) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:29:57.220-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:29:57.221-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:29:57.221-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:29:57.227-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:29:57.226-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:29:57.228-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:29:57.249-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.034 seconds
[2022-11-07T23:30:32.644-0300] {processor.py:156} INFO - Started process (PID=965756) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:30:32.646-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:30:32.647-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:30:32.647-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:30:32.650-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:30:32.649-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:30:32.651-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:30:32.673-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.031 seconds
[2022-11-07T23:31:09.509-0300] {processor.py:156} INFO - Started process (PID=965828) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:31:09.511-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:31:09.512-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:31:09.512-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:31:09.517-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:31:09.516-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:31:09.518-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:31:09.541-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.035 seconds
[2022-11-07T23:31:43.550-0300] {processor.py:156} INFO - Started process (PID=965894) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:31:43.553-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:31:43.554-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:31:43.554-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:31:43.561-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:31:43.559-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:31:43.562-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:31:43.592-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.050 seconds
[2022-11-07T23:32:22.087-0300] {processor.py:156} INFO - Started process (PID=966103) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:32:22.091-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:32:22.093-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:32:22.092-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:32:22.098-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:32:22.097-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:32:22.098-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:32:22.123-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.043 seconds
[2022-11-07T23:32:52.493-0300] {processor.py:156} INFO - Started process (PID=966163) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:32:52.495-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:32:52.496-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:32:52.496-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:32:52.500-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:32:52.499-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:32:52.501-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:32:52.526-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.036 seconds
[2022-11-07T23:33:29.727-0300] {processor.py:156} INFO - Started process (PID=966237) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:33:29.730-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:33:29.731-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:33:29.731-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:33:29.740-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:33:29.738-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:33:29.741-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:33:29.769-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.049 seconds
[2022-11-07T23:34:07.329-0300] {processor.py:156} INFO - Started process (PID=966311) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:34:07.332-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:34:07.333-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:34:07.333-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:34:07.337-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:34:07.336-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:34:07.337-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:34:07.359-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.035 seconds
[2022-11-07T23:34:44.417-0300] {processor.py:156} INFO - Started process (PID=966387) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:34:44.419-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:34:44.420-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:34:44.420-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:34:44.423-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:34:44.422-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:34:44.424-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:34:44.447-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.034 seconds
[2022-11-07T23:35:15.117-0300] {processor.py:156} INFO - Started process (PID=966448) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:35:15.119-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:35:15.120-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:35:15.119-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:35:15.125-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:35:15.124-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:35:15.126-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:35:15.150-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.038 seconds
[2022-11-07T23:35:46.935-0300] {processor.py:156} INFO - Started process (PID=966512) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:35:46.938-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:35:46.940-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:35:46.939-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:35:46.947-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:35:46.946-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:35:46.948-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:35:46.982-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.053 seconds
[2022-11-07T23:36:27.769-0300] {processor.py:156} INFO - Started process (PID=966591) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:36:27.772-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:36:27.773-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:36:27.773-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:36:27.777-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:36:27.776-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:36:27.778-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:36:27.804-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.039 seconds
[2022-11-07T23:37:06.174-0300] {processor.py:156} INFO - Started process (PID=966669) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:37:06.177-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:37:06.178-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:37:06.178-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:37:06.184-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:37:06.183-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:37:06.185-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:37:06.212-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.043 seconds
[2022-11-07T23:37:41.888-0300] {processor.py:156} INFO - Started process (PID=966869) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:37:41.913-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:37:41.914-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:37:41.913-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:37:41.920-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:37:41.919-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:37:41.921-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:37:41.955-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.084 seconds
[2022-11-07T23:38:17.554-0300] {processor.py:156} INFO - Started process (PID=966939) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:38:17.557-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:38:17.557-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:38:17.557-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:38:17.561-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:38:17.560-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:38:17.561-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:38:17.585-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.034 seconds
[2022-11-07T23:38:47.804-0300] {processor.py:156} INFO - Started process (PID=966997) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:38:47.805-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:38:47.806-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:38:47.806-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:38:47.810-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:38:47.809-0300] {dagbag.py:330} ERROR - Failed to import: /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/renato/Documentos/datapipeline/.env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-07T23:38:47.810-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:38:47.832-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.032 seconds
[2022-11-07T23:39:18.740-0300] {processor.py:156} INFO - Started process (PID=967077) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:39:18.742-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:39:18.743-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:39:18.742-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:39:18.764-0300] {processor.py:768} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:39:18.873-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:39:18.873-0300] {manager.py:507} INFO - Created Permission View: can edit on DAG:twitter_dag
[2022-11-07T23:39:18.892-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:39:18.892-0300] {manager.py:507} INFO - Created Permission View: can read on DAG:twitter_dag
[2022-11-07T23:39:18.906-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:39:18.905-0300] {manager.py:507} INFO - Created Permission View: can delete on DAG:twitter_dag
[2022-11-07T23:39:18.906-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:39:18.906-0300] {dag.py:2573} INFO - Sync 1 DAGs
[2022-11-07T23:39:18.915-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:39:18.915-0300] {dag.py:2594} INFO - Creating ORM DAG for twitter_dag
[2022-11-07T23:39:18.926-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:39:18.926-0300] {dag.py:3324} INFO - Setting next_dagrun for twitter_dag to 2022-11-07T23:39:18.756169+00:00, run_after=2022-11-08T23:39:18.756169+00:00
[2022-11-07T23:39:18.966-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.229 seconds
[2022-11-07T23:39:29.733-0300] {processor.py:156} INFO - Started process (PID=967096) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:39:29.733-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:39:29.734-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:39:29.734-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:39:29.760-0300] {processor.py:768} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:39:29.767-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:39:29.767-0300] {dag.py:2573} INFO - Sync 1 DAGs
[2022-11-07T23:39:29.786-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:39:29.786-0300] {dag.py:3324} INFO - Setting next_dagrun for twitter_dag to 2022-11-07T23:39:29.751147+00:00, run_after=2022-11-08T23:39:29.751147+00:00
[2022-11-07T23:39:29.810-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.080 seconds
[2022-11-07T23:40:11.050-0300] {processor.py:156} INFO - Started process (PID=967181) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:40:11.053-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:40:11.053-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:40:11.053-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:40:11.086-0300] {processor.py:768} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:40:11.160-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:40:11.160-0300] {dag.py:2573} INFO - Sync 1 DAGs
[2022-11-07T23:40:11.187-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:40:11.187-0300] {dag.py:3324} INFO - Setting next_dagrun for twitter_dag to 2022-11-07T23:40:11.068702+00:00, run_after=2022-11-08T23:40:11.068702+00:00
[2022-11-07T23:40:11.236-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.189 seconds
[2022-11-07T23:40:50.384-0300] {processor.py:156} INFO - Started process (PID=967256) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:40:50.389-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:40:50.390-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:40:50.390-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:40:50.416-0300] {processor.py:768} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:40:50.455-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:40:50.455-0300] {dag.py:2573} INFO - Sync 1 DAGs
[2022-11-07T23:40:50.470-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:40:50.470-0300] {dag.py:3324} INFO - Setting next_dagrun for twitter_dag to 2022-11-07T23:40:50.406667+00:00, run_after=2022-11-08T23:40:50.406667+00:00
[2022-11-07T23:40:50.495-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.115 seconds
[2022-11-07T23:41:24.155-0300] {processor.py:156} INFO - Started process (PID=967320) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:41:24.156-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:41:24.157-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:41:24.156-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:41:24.186-0300] {processor.py:768} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:41:24.232-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:41:24.232-0300] {dag.py:2573} INFO - Sync 1 DAGs
[2022-11-07T23:41:24.250-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:41:24.250-0300] {dag.py:3324} INFO - Setting next_dagrun for twitter_dag to 2022-11-07T23:41:24.169966+00:00, run_after=2022-11-08T23:41:24.169966+00:00
[2022-11-07T23:41:24.277-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.127 seconds
[2022-11-07T23:41:54.702-0300] {processor.py:156} INFO - Started process (PID=967387) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:41:54.703-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:41:54.704-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:41:54.703-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:41:54.729-0300] {processor.py:768} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:41:54.777-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:41:54.777-0300] {dag.py:2573} INFO - Sync 1 DAGs
[2022-11-07T23:41:54.791-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:41:54.791-0300] {dag.py:3324} INFO - Setting next_dagrun for twitter_dag to 2022-11-07T23:41:54.719142+00:00, run_after=2022-11-08T23:41:54.719142+00:00
[2022-11-07T23:41:54.851-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.156 seconds
[2022-11-07T23:42:28.186-0300] {processor.py:156} INFO - Started process (PID=967581) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:42:28.188-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:42:28.189-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:42:28.189-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:42:28.221-0300] {processor.py:768} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:42:28.269-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:42:28.269-0300] {dag.py:2573} INFO - Sync 1 DAGs
[2022-11-07T23:42:28.284-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:42:28.284-0300] {dag.py:3324} INFO - Setting next_dagrun for twitter_dag to 2022-11-07T23:42:28.207903+00:00, run_after=2022-11-08T23:42:28.207903+00:00
[2022-11-07T23:42:28.311-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.129 seconds
[2022-11-07T23:43:07.224-0300] {processor.py:156} INFO - Started process (PID=967656) to work on /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:43:07.227-0300] {processor.py:758} INFO - Processing file /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-07T23:43:07.228-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:43:07.228-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:43:07.261-0300] {processor.py:768} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py
[2022-11-07T23:43:07.305-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:43:07.305-0300] {dag.py:2573} INFO - Sync 1 DAGs
[2022-11-07T23:43:07.321-0300] {logging_mixin.py:117} INFO - [2022-11-07T23:43:07.320-0300] {dag.py:3324} INFO - Setting next_dagrun for twitter_dag to 2022-11-07T23:43:07.249903+00:00, run_after=2022-11-08T23:43:07.249903+00:00
[2022-11-07T23:43:07.349-0300] {processor.py:178} INFO - Processing /home/renato/Documentos/datapipeline/airflow/dags/twitter_dag.py took 0.133 seconds
